export const projects = [
  {
    id: 1,
    title: "Tic Tac Toe",
    thumbnail: "img/projects/tictactoe.png",
    alt: "tic tac toe project thumbnail",
    videoURL: "video/tictactoe.mp4",
    liveSite: "https://nicopom.github.io/Rock-Paper-Scissors/",
    github: "https://github.com/NicoPom/Rock-Paper-Scissors",
    description:
      "A simple tic tac toe game made with pure JavaScript, HTML and CSS.",
  },
  {
    id: 2,
    title: "Advice Generator",
    thumbnail: "img/projects/advice_generator.png",
    alt: "advice generator project thumbnail",
    videoURL: "video/advice_generator.mp4",
    liveSite: "https://nicopom.github.io/Advice-Generator-App-Main/",
    github: "https://github.com/NicoPom/Advice-Generator-App-Main",
    description:
      "A simple advice generator made with pure JavaScript, HTML, CSS and the Advice Slip API.",
  },
  {
    id: 3,
    title: "E-Commerce Product Page",
    thumbnail: "img/projects/ecommerce_product_page.png",
    alt: "e-commerce product page project thumbnail",
    videoURL: "video/ecommerce_product_page.mp4",
    liveSite: "https://nicopom.github.io/ecommerce-product-page/",
    github: "https://github.com/NicoPom/ecommerce-product-page",
    description:
      "An e-commerce product page made with pure Javascript, HTML and CSS.",
  },
  {
    id: 4,
    title: "Sign Up Form",
    thumbnail: "img/projects/sign_up_form.png",
    alt: "sign up form project thumbnail",
    videoURL: "video/sign_up_form.mp4",
    liveSite: "https://nicopom.github.io/sign-up-form/",
    github: "https://github.com/NicoPom/sign-up-form",
    description: "A sign up form made with pure Javascript, HTML and CSS.",
  },
  {
    id: 5,
    title: "Travel Journal React App",
    thumbnail: "img/projects/travel_journal.png",
    alt: "travel journal project thumbnail",
    videoURL: "video/travel_journal.mp4",
    liveSite: "https://transcendent-sunshine-c02b2d.netlify.app/",
    github: "https://github.com/NicoPom/travel-journal-react",
    description: "A travel journal app made with React.JS, HTML and CSS.",
  },
];
