export const projects = [
  {
    id: 1,
    title: "Tic Tac Toe",
    thumbnail: "img/tiktaktoe.png",
    alt: "project_thumbnail",
    videoURL: "video/tiktaktoe.mp4",
    liveSite: "https://nicopom.github.io/Rock-Paper-Scissors/",
    github: "https://github.com/NicoPom/Rock-Paper-Scissors",
  },
  {
    id: 2,
    title: "Tic Tac Toe",
    thumbnail: "img/tictactoe.png",
    alt: "project_thumbnail",
    videoURL: "video/scrim.mp4",
    liveSite: "https://nicopom.github.io/Rock-Paper-Scissors/",
    github: "https://github.com/NicoPom/Rock-Paper-Scissors",
  },
  {
    id: 3,
    title: "Tic Tac Toe",
    thumbnail: "img/tictactoe.png",
    alt: "project_thumbnail",
    videoURL: "video/scrim.mp4",
    liveSite: "https://nicopom.github.io/Rock-Paper-Scissors/",
    github: "https://github.com/NicoPom/Rock-Paper-Scissors",
  },
  {
    id: 4,
    title: "Tic Tac Toe",
    thumbnail: "img/tictactoe.png",
    alt: "project_thumbnail",
    videoURL: "video/scrim.mp4",
    liveSite: "https://nicopom.github.io/Rock-Paper-Scissors/",
    github: "https://github.com/NicoPom/Rock-Paper-Scissors",
  },
];
